import { pgTable, text, integer, boolean, timestamp, jsonb } from 'drizzle-orm/pg-core'

export const user = pgTable('user', {
  id: text('id').primaryKey(), name: text('name').notNull(), email: text('email').notNull().unique(), emailVerified: boolean('emailVerified').notNull().default(false), image: text('image'), createdAt: timestamp('createdAt').notNull().defaultNow(), updatedAt: timestamp('updatedAt').notNull().defaultNow(),
})
export const session = pgTable('session', { id: text('id').primaryKey(), expiresAt: timestamp('expiresAt').notNull(), token: text('token').notNull().unique(), createdAt: timestamp('createdAt').notNull().defaultNow(), updatedAt: timestamp('updatedAt').notNull().defaultNow(), ipAddress: text('ipAddress'), userAgent: text('userAgent'), userId: text('userId').notNull() })
export const account = pgTable('account', { id: text('id').primaryKey(), accountId: text('accountId').notNull(), providerId: text('providerId').notNull(), userId: text('userId').notNull(), accessToken: text('accessToken'), refreshToken: text('refreshToken'), idToken: text('idToken'), accessTokenExpiresAt: timestamp('accessTokenExpiresAt'), refreshTokenExpiresAt: timestamp('refreshTokenExpiresAt'), scope: text('scope'), password: text('password'), createdAt: timestamp('createdAt').notNull().defaultNow(), updatedAt: timestamp('updatedAt').notNull().defaultNow() })
export const verification = pgTable('verification', { id: text('id').primaryKey(), identifier: text('identifier').notNull(), value: text('value').notNull(), expiresAt: timestamp('expiresAt').notNull(), createdAt: timestamp('createdAt').notNull().defaultNow(), updatedAt: timestamp('updatedAt').notNull().defaultNow() })
export const playerProfile = pgTable('player_profile', { userId: text('userId').primaryKey(), displayName: text('displayName').notNull(), wins: integer('wins').notNull().default(0), losses: integer('losses').notNull().default(0), coins: integer('coins').notNull().default(0), createdAt: timestamp('createdAt').notNull().defaultNow(), updatedAt: timestamp('updatedAt').notNull().defaultNow() })
export const fighterUnlock = pgTable('fighter_unlock', { id: text('id').primaryKey(), userId: text('userId').notNull(), fighterId: text('fighterId').notNull(), unlocked: boolean('unlocked').notNull().default(false), level: integer('level').notNull().default(1), createdAt: timestamp('createdAt').notNull().defaultNow() })
export const gameRoom = pgTable('game_room', { id: text('id').primaryKey(), code: text('code').notNull().unique(), hostUserId: text('hostUserId').notNull(), guestUserId: text('guestUserId'), status: text('status').notNull().default('waiting'), state: jsonb('state'), updatedAt: timestamp('updatedAt').notNull().defaultNow(), createdAt: timestamp('createdAt').notNull().defaultNow() })
export const match = pgTable('match', { id: text('id').primaryKey(), roomId: text('roomId'), winnerUserId: text('winnerUserId'), status: text('status').notNull(), result: jsonb('result'), startedAt: timestamp('startedAt'), completedAt: timestamp('completedAt'), createdAt: timestamp('createdAt').notNull().defaultNow() })
export const matchParticipant = pgTable('match_participant', { id: text('id').primaryKey(), matchId: text('matchId').notNull(), userId: text('userId').notNull(), fighterId: text('fighterId').notNull(), side: text('side').notNull(), createdAt: timestamp('createdAt').notNull().defaultNow() })

export const schema = { user, session, account, verification, playerProfile, fighterUnlock, gameRoom, match, matchParticipant }
