kind = "web"
previewPath = "/"
title = "BARBIEGame"
version = "1.0.0"
id = "artifacts/barbie-game"
router = "path"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 18935

[services.development]
run = "pnpm --filter @workspace/barbie-game run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/barbie-game", "run", "build" ]
serve = "static"
publicDir = "artifacts/barbie-game/dist/public"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "18935"
BASE_PATH = "/"
